server:
  port: 0

spring:
  application:
    name: wm-dict-manager
  redis:
    host: 111.230.220.114
  datasource:
    name: test
    url: jdbc:mysql://111.230.220.114:3306/weiming?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: average
    password: Average123!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
        
    
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int(4000,10000)}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
   
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.github.ycg000344.weiming.dictmanager.entity
   
logging:
  level:
    org.github.ycg000344.weiming.dictmanager.mapper: debug