spring: 
  mail:
    default-encoding: UTF-8
    host: smtp-mail.outlook.com
    password: weiming123
    port: 25
    protocol: smtp
    test-connection: false
    username: wm.root@outlook.com
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
          quitwait: false
        transport: 
          protocol: smtps
  rabbitmq: 
    host: 111.230.220.114
    username: admin
    password: 123456
    port: 5672
  application:
    name: email-send-server
  boot:
    admin:
      client:
        url:
        - "http://127.0.0.1:8000"
server:
  port: 0

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int(4000,10000)}}
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 20