server:
  port: 0

spring:
  application:
    name: wm-basic-manager
  redis:
    host: 111.230.220.114
  datasource:
    name: weiming
    url: jdbc:mysql://111.230.220.114:3306/weiming?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: average
    password: Average123!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #dataSource Pool configuration
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: {stat,wall,log4j}
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  cache:
    type: redis
    
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.int(4000,10000)}}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
   
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.github.ycg000344.weiming.application.basicmanager.entity
   
logging:
  level:
    org.github.ycg000344.weiming.application.basicmanager.mapper: debug
    
    
###                                              #######
###                    _ooOoo_                   #######
###                   o8888888o                  #######
###                   88" . "88                  #######
###                   (| -_- |)                  #######
###                    O\ = /O                   #######
###                ____/`---'\____               #######
###              .   ' \\| |// `.                #######
###               / \\||| 1 |||// \              #######
###             / _||||| -9- |||||- \            #######
###               | | \\\ 9 /// | |              #######
###             | \_| ''\-8-/'' | |              #######
###              \ .-\__ `0` ___/-. /            #######
###           ___`. .' /--2--\ `. . __           #######
###        ."" '< `.___\_<0>_/___.' >'"".        #######
###       | | : `- \`.;`\ 2 /`;.`/ - ` : | |     #######
###         \ \ `-. \_ __\ /__ _/ .-` / /        #######
### ======`-.____`-.___\_____/___.-`____.-'======#######
###                    `=---='                   #######
###                                              #######
###...............自定义配置项....................#######

weiming: 
  basicmanager: 
    druid: 
      loginname: admin
      password: admin
    defaultPwd: qqq123









