server:
  port: 8761
spring:
  application:
    name: eureka-server
  rabbitmq:
    host: 111.230.220.114
    port: 5672
    username: admin
    password: 123456
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false  # 多个eureka 设置 true
    fetchRegistry: false       # 多个eureka 设置 true
    service-url:
      defaultZone: http://${eureka.host:localhost}:8761/eureka
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 20000  #缩小清理无效节点的时间间隔
    
################################
config:
  rabbitmq:
    queue: email